// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID     string     `json:"id"`
	Author string     `json:"author"`
	Text   string     `json:"text"`
	Time   time.Time  `json:"time"`
	Childs []*Comment `json:"childs,omitempty"`
}

type CommentsResult struct {
	Comments []*Comment `json:"comments,omitempty"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Mutation struct {
}

type NewComment struct {
	Author string    `json:"author"`
	Text   string    `json:"text"`
	Time   time.Time `json:"time"`
}

type NewPost struct {
	Author        string    `json:"author"`
	Title         string    `json:"title"`
	Text          string    `json:"text"`
	Time          time.Time `json:"time"`
	IsCommentable *bool     `json:"isCommentable,omitempty"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type Post struct {
	ID            string    `json:"id"`
	Author        string    `json:"author"`
	Title         string    `json:"title"`
	Text          string    `json:"text"`
	Time          time.Time `json:"time"`
	IsCommentable *bool     `json:"isCommentable,omitempty"`
}

type Query struct {
}

type ShortPost struct {
	ID     string `json:"id"`
	Author string `json:"author"`
	Title  string `json:"title"`
}

type Subscription struct {
}
